# name: Apply Infrastructure

# on:
#   push:
#     branches:
#       - main

# jobs:
#   apply:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Terraform Init
#         working-directory: examples/simple
#         env:
#           TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: terraform init

#       - name: Terraform Plan
#         working-directory: examples/simple
#         env:
#           TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: terraform plan

#       - name: Terraform Apply
#         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#         working-directory: examples/simple
#         env:
#           TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: terraform apply -auto-approve


# ---
# name: Validate Terraform Module

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   validate:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Terraform Validate
#         working-directory: modules/ec2-instance
#         run: terraform validate
# ---
# name: Publish Terraform Module

# on:
#   push:
#     tags:
#       - "v*.*.*"  # Trigger on semantic version tags (e.g., v1.0.0)

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Publish to Terraform Cloud
#         working-directory: modules/ec2-instance
#         env:
#           TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
#         run: |
#           echo "Publishing module to Terraform Cloud"
#           terraform init
#           terraform validate
