# name: Publish Terraform Module

# on:
#   push:
#     tags:
#       - "v*.*.*"  # Trigger on semantic version tags (e.g., v1.0.0)

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Publish to Terraform Cloud
#         working-directory: modules/ec2-instance
#         env:
#           TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
#         run: |
#           echo "Publishing module to Terraform Cloud"
#           terraform init
#           terraform validate
