# name: Terraform Workflows

# on:
#   push:
#     branches:
#       - main         # Trigger on push to main branch
#     tags:
#       - "v*.*.*"     # Trigger on semantic version tags (e.g., v1.0.0)
#   pull_request:
#     branches:
#       - main         # Trigger on pull requests targeting main

# jobs:
#   # Job 1: Validate Terraform Module
#   validate:
#     name: Validate Terraform Module
#     runs-on: ubuntu-latest

#     env:
#       TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # Terraform Cloud Token
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       TF_VAR_region: "us-east-2"
#       TF_VAR_instance_ami: "ami-0c11a84584d4e09dd"
#       TF_VAR_instance_type: "t2.micro"
#       TF_VAR_key_name: "my-key-pair"
#       TF_VAR_volume_size: "40"
#       TF_VAR_tags: '{"Name":"ExampleInstance","Environment":"Test"}'

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Configure Terraform credentials
#         run: |
#           mkdir -p ~/.terraform.d
#           echo '{"credentials":{"app.terraform.io":{"token":"${TFC_TOKEN}"}}}' > ~/.terraform.d/credentials.tfrc.json

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Terraform Init
#         working-directory: modules/ec2-instance
#         run: terraform init

#       - name: Terraform Validate
#         working-directory: modules/ec2-instance
#         run: terraform validate

#   # Job 2: Publish Terraform Module
#   publish:
#     name: Publish Terraform Module
#     runs-on: ubuntu-latest

#     env:
#       TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # Terraform Cloud Token
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       TF_VAR_region: "us-east-2"
#       TF_VAR_instance_ami: "ami-0c11a84584d4e09dd"
#       TF_VAR_instance_type: "t2.micro"
#       TF_VAR_key_name: "my-key-pair"
#       TF_VAR_volume_size: "40"
#       TF_VAR_tags: '{"Name":"ExampleInstance","Environment":"Test"}'

#     steps:
#       - name: Debug GitHub Ref
#         run: echo "GITHUB_REF is $GITHUB_REF"

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Configure Terraform credentials
#         run: |
#           mkdir -p ~/.terraform.d
#           echo '{"credentials":{"app.terraform.io":{"token":"${TFC_TOKEN}"}}}' > ~/.terraform.d/credentials.tfrc.json

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Terraform Init
#         working-directory: modules/ec2-instance
#         run: terraform init

#       - name: Terraform Format Check
#         working-directory: modules/ec2-instance
#         run: terraform fmt -check

#       - name: Terraform Validate
#         working-directory: modules/ec2-instance
#         run: terraform validate

#       - name: Publish to Terraform Cloud
#         working-directory: modules/ec2-instance
#         run: |
#           echo "Publishing module to Terraform Cloud"
#           terraform plan
name: Terraform Workflows

on:
  push:
    branches:
      - main         # Trigger on push to main branch
    tags:
      - "v*.*.*"     # Trigger on semantic version tags (e.g., v1.0.0)
  pull_request:
    branches:
      - main         # Trigger on pull requests targeting main 

jobs:
  # Job: Push Configuration to TFC
  push-to-tfc:
    name: Push Configuration to TFC
    runs-on: ubuntu-latest

    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: "us-east-2"
      TF_VAR_instance_ami: "ami-0c11a84584d4e09dd"
      TF_VAR_instance_type: "t2.micro"
      TF_VAR_key_name: "my-key-pair"
      TF_VAR_volume_size: "40"
      TF_VAR_tags: '{"Name":"ExampleInstance","Environment":"Test"}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Terraform credentials
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials":{"app.terraform.io":{"token":"${TFC_TOKEN}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Terraform Init
        working-directory: examples/simple
        run: terraform init

      - name: Terraform Plan
        working-directory: examples/simple
        run: terraform plan
