name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Export TFC Token for Terraform Cloud
      - name: Set TFC Token
        run: echo "TFC_TOKEN=${{ secrets.TFC_TOKEN }}" >> $GITHUB_ENV

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Initialize Terraform in the correct directory
      - name: Terraform Init
        working-directory: modules/ec2-instance
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        working-directory: modules/ec2-instance
        run: terraform validate

      # Plan Terraform changes
      - name: Terraform Plan
        working-directory: modules/ec2-instance
        run: terraform plan

      # (Optional) Terraform Apply
      # Run this only for specific events, e.g., on pushes to `main`.
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: modules/ec2-instance
        run: terraform apply -auto-approve
