# name: Terraform Workflows

# on:
#   push:
#     branches:
#       - main
#     tags:
#       - "v*.*.*"
#   pull_request:
#     branches:
#       - main

# jobs:
#   validate:
#     name: Validate and Format Terraform Code
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Debug Directory Structure
#         run: ls -R

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Terraform Init
#         run: terraform init

#       - name: Check Terraform Format
#         run: terraform fmt -check

#       - name: Validate Terraform
#         run: terraform validate

#   publish:
#     name: Publish Terraform Module to TFC Registry
#     runs-on: ubuntu-latest
#     needs: validate

#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: "us-east-2"
#       TFC_TOKEN: ${{ secrets.TFC_TOKEN }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Debug Directory Structure
#         run: ls -R

#       - name: Configure Terraform credentials
#         run: |
#           mkdir -p ~/.terraform.d
#           echo '{"credentials":{"app.terraform.io":{"token":"${{ secrets.TFC_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.5.6"

#       - name: Terraform Init (Module)
#         run: terraform init

#       - name: Publish to TFC Registry
#         run: |
#           echo "Publishing module to Terraform Cloud Registry"
#           terraform plan -out=tfplan
name: Terraform Workflows

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate and Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Terraform Init
        working-directory: .
        run: terraform init

      - name: Check Terraform Format
        working-directory: .
        run: terraform fmt -check

      - name: Validate Terraform
        working-directory: .
        run: terraform validate

  publish:
    name: Publish Terraform Module to TFC
    runs-on: ubuntu-latest
    needs: validate

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-2"
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
      TF_VAR_region: "us-east-2"
      TF_VAR_instance_ami: "ami-123fakeami"
      TF_VAR_instance_type: "t2.micro"
      TF_VAR_key_name: "fake-key-pair"
      TF_VAR_volume_size: 50
      TF_VAR_tags: '{"Name":"ExampleInstance","Environment":"Test"}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug AWS Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:0:4}****"
          echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
      - name: Debug Directory Structure
        run: ls -R

      
      - name: Configure Terraform credentials
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials":{"app.terraform.io":{"token":"${{ secrets.TFC_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Terraform Init
        working-directory: .
        run: terraform init

      - name: Terraform Plan
        working-directory: .
        run: terraform plan
