name: Terraform with Terraform Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Export TFC_TOKEN
      - name: Export Terraform Cloud Token
        run: echo "TFC_TOKEN=${{ secrets.TFC_TOKEN }}" >> $GITHUB_ENV

      # Step 3: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.6'

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # # Step 6: Terraform Apply (optional)
      # - name: Terraform Apply
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: terraform apply -auto-approve
