name: Terraform Workflows

on:
  push:
    branches:
      - main                # Trigger on push to main branch
    tags:
      - "v*.*.*"            # Trigger on semantic version tags (e.g., v1.0.0)
  pull_request:
    branches:
      - main                # Trigger on pull requests targeting main

jobs:
  # Job 1: Validate and Format Terraform Code
  validate:
    name: Validate and Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Terraform Init
        working-directory: modules/ec2-instance
        run: terraform init

      - name: Check Terraform Format
        working-directory: modules/ec2-instance
        run: terraform fmt -check

      - name: Validate Terraform
        working-directory: modules/ec2-instance
        run: terraform validate

  # Job 2: Publish Module to Terraform Cloud
  publish:
    name: Publish Terraform Module to TFC
    runs-on: ubuntu-latest
    needs: validate       # Ensure `validate` job completes successfully
    if: contains(github.ref, 'refs/tags/v')  # Run only for semantic version tags

    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: "us-east-2"
      TF_VAR_instance_ami: "ami-0c11a84584d4e09dd"
      TF_VAR_instance_type: "t2.micro"
      TF_VAR_key_name: "my-key-pair"
      TF_VAR_volume_size: "40"
      TF_VAR_tags: '{"Name":"ExampleInstance","Environment":"Test"}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug GITHUB_REF
        run: echo "GITHUB_REF is $GITHUB_REF"

      - name: Configure Terraform credentials
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials":{"app.terraform.io":{"token":"${{ secrets.TFC_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Terraform Init
        working-directory: examples/simple
        run: terraform init

      - name: Terraform Plan
        working-directory: examples/simple
        run: terraform plan

      - name: Publish to Terraform Cloud Registry
        working-directory: modules/ec2-instance
        run: |
          echo "Publishing module to Terraform Cloud Registry"
          terraform plan
