name: Terraform Workflows

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  # Job 1: Validate and Format Terraform Code
  validate:
    name: Validate and Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Terraform Init
        working-directory: modules/ec2-instance
        run: terraform init

      - name: Check Terraform Format
        working-directory: modules/ec2-instance
        run: terraform fmt -check

      - name: Validate Terraform
        working-directory: modules/ec2-instance
        run: terraform validate

  # Job 2: Determine and Publish Release
  publish:
    name: Publish Terraform Module to TFC
    runs-on: ubuntu-latest
    needs: validate

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for semantic-release
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Semantic Release
        run: npx semantic-release

      - name: Configure Terraform credentials
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials":{"app.terraform.io":{"token":"${{ secrets.TFC_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Terraform Init
        working-directory: examples/simple
        run: terraform init

      - name: Terraform Plan
        working-directory: examples/simple
        run: terraform plan
